# Site settings
title: Global Blockchain Compliance Hub
email: chentian@neo.org
description: The repository for global blockchain compliance
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://neo-project.github.io/global-blockchain-compliance-hub/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: none
future : true

theme: jekyll-theme-minimal

menu:
  categories: /categories 

scheme: Pisces
